name: Code Style and Format
on: [pull_request]
jobs:
  ruff:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Check Imports
        uses: chartboost/ruff-action@v1
        with:
          version: 0.6.3
          args: check --select I
      - name: Linter
        uses: chartboost/ruff-action@v1
        with:
          version: 0.6.3
          args: check
